# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
# 网站标题
title: '偷掉月亮'
#网站副标题
subtitle: '我们一起去偷月亮吧'
#网站描述
description: '这是我的博客网站'
# 网站关键词，便于别人搜索到你
keywords: '偷掉月亮'
# 作者名称
author: '偷掉月亮的阿硕'
# 语言
language: zh-CN
#时区
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
# 自己网站的网址
url: https://moonshuo.cn/
# 永久链接，这里不建议使用这个，后面我们会进行优化
permalink: posts/:abbrlink.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly
baidu_url_submit:
  count: 10               # 提交最新的多少个链接
  host: https://moonshuo.cn/   # 在百度站长平台中添加的域名
  token:      # 秘钥
  path: baidu_urls.txt   # 文本文档的地址， 新链接会保存在此文本文档里
# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
- type: baidu_url_submitter
- type: cos-cdn
  cloud: tencent
  bucket:
  region:
  cdnEnable: true
  secretId:
  secretKey:

search:
  path: search.xml
  field: all # post:文章范围、page:页面范围、all:覆盖所有
  content: true # 内容是否包含每一篇文章的全部内容
  template:  # ./search.xml 指定定制的XML模板

calendar:
  single: true
  root: calendar/

butterfly_article_double_row:
  enable: true

douban:
  id:
  book:
    path: books
    title: '我的书籍'
    quote: '读书之法无他，惟是笃志虚心，反复详玩，为有功耳'
  movie:
    path: movies
    title: 'This is my movie title'
    quote: 'This is my movie quote'
  game:
    path: games
    title: 'This is my game title'
    quote: 'This is my game quote'
  timeout: 10000 

